/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sphereWizard;

import java.io.IOException;

import sphereWizard.Calculator.CircularityCalculator;
import sphereWizard.Exceptions.EmptyListException;
import sphereWizard.Exceptions.FlowOutputNotRecognizedException;
import sphereWizard.Exceptions.UnitNotRecognizedException;
import sphereWizard.Exporter.ReportMaker;
import sphereWizard.Interfaces.sendFileData;
import sphereWizard.Interfaces.sendModeledData;
import sphereWizard.ProductSystem.ProductSystem;
import sphereWizard.ProductSystem.ProductSystemData;

/**
 * Demo
 */
public class Demo {

    public static void main(String[] args) {
        // sendFileData productSystemdata = new ProductSystemData();

        // sendModeledData ps;

        // try {
        //     productSystemdata.getProductSystemData().readCsv("FlowTableDemo.csv", ";");

        //     System.out.println(productSystemdata);
            
        //     ps = new ProductSystem(productSystemdata, 12, 52);

        //     ps.getProductSystem().calculateAllMethods();

        //     CircularityCalculator cc = new CircularityCalculator(ps);
        //     cc.calculateCircularityIndex();
        //     ReportMaker exporter = new ReportMaker(ps, cc);
        //     exporter.exportInformationToCsv("C:\\Users\\hugui\\Desktop\\testFilePath.csv");

        // } catch (EmptyListException e) {
        //     e.printStackTrace();
        // } catch (NumberFormatException e) {
        //     e.printStackTrace();
        // } catch (UnitNotRecognizedException e) {
        //     e.printStackTrace();
        // } catch (FlowOutputNotRecognizedException e) {
        //     e.printStackTrace();
        // } catch (IOException e) {
        //     e.printStackTrace();
        // }

    }
}
